### ISSUE TITLE
Unable to build package using Xcode

### ISSUE THREAD

**Issue by mattmassicotte** [apple/swift-cassandra-client#14]
Here's what I did:

- Fork repo
- Clone
- `git submodule update --init --recursive --remote`

The `swift-cassandra-driver` fails to build, because libuv is looking for `sys/epoll.h` on my system. Did I do something dumb and miss the instructions for local building?

**Comment by yim-lee** [comment]
I can't reproduce this in Xcode 14.1 (14B47b). I don't think I did anything special. Curious to see if others have run into the same issue as well.

**Comment by mattmassicotte** [comment]
Hmm, I don't understand what the difference could. To fix this, I had to add the following to the `libuvExclude` variable for `!os(Linux)`

    "./libuv/src/unix/linux.c",

However, now I'm hitting a linking failure: 

    "datastax::internal::core::OpenSslContext::set_min_protocol_version(CassSslTlsVersion_)", referenced from:
      vtable for datastax::internal::core::OpenSslContext in CDataStaxDriver.o

**Comment by mattmassicotte** [comment]
Ahh, user error! The correct method is:

`git submodule update --init`

`--recursive` isn't needed in this case, but the real problem was my use of `--remote`. That checks ignores the recorded commit in the submodule.
